### ISSUE TITLE
CentralNic: Show the Registrar IANA ID for .frl on the correct place 

### ISSUE THREAD

**Issue by janwillemstegink** [janwillemstegink/rdap.hostingtool.nl#19]
CentralNic: The Registrar IANA ID for .frl does not show up on the correct place 
The IANA ID of Metaregistrar is 2288.
https://rdap.hostingtool.nl/modeling_domain/index.php?language=2&domain=registreer.frl

![image](https://github.com/user-attachments/assets/88487535-5e59-46c5-91da-bd5b65f1a965)

**Comment by xaben** [comment]
@janwillemstegink I'm not sure I understand what the issue is, we are exposing the IANA id of a registrar inside the entity in 2 places, handle and publicIds. As far as I'm aware these are the correct places, where they should be exposed:

https://www.icann.org/en/system/files/files/rdap-technical-implementation-guide-21feb24-en.pdf section 2.4.1

https://www.icann.org/en/system/files/files/rdap-response-profile-21feb24-en.pdf section 2.4.3

Extracted sequence from https://rdap.centralnic.com/frl/domain/registreer.frl:

```json
{
  "objectClassName": "entity",
  "handle": "2288",
  "roles": [
    "registrar"
  ],

...

  "publicIds": [
    {
      "type": "IANA Registrar ID",
      "identifier": "2288"
    }
  ]
}

**Comment by janwillemstegink** [comment]
Compared https://client.rdap.org/?type=domain&object=registreer.frl

My code:
$registrar_iana_id = $obj['entities'][0]['publicIds'][0]['identifier'];	
did lead to output with entity 1:
$registrar_iana_id = $obj['entities'][1]['publicIds'][0]['identifier'];

The dynamic working code is now:

if ($key2 == $entity_registrar and $key3 == 'publicIds')	{
	if ($key5 == 'type' and $value5 == 'IANA Registrar ID')	{
		$registrar_iana_id = $value4['identifier'];
	}
}
